version: "3"

services:
    Victim:
        image: ubuntu:20.04
        container_name: victim
        privileged: true
        tty: true
        cap_add:
                - ALL
#        sysctls:
#                - net.ipv4.ip_forward=1
#        networks:
#            net-10.9.0.0:
#                ipv4_address: 10.9.0.5
        command: bash -c "
                      echo 0 > /proc/sys/kernel/randomize_va_space &&
                      export LD_LIBRARY_PATH=/home/code &&
                      tail -f /dev/null"
        volumes:
            - code:/home/code

    Attacker:
        image: ubuntu:20.04
        container_name: attacker
        privileged: true
        tty: true
#        cap_add:
#                - ALL
#        networks:
#            net-192.168.60.0:
#                ipv4_address: 192.168.60.5
        command: bash -c "
                      echo 0 > /proc/sys/kernel/randomize_va_space &&
                      export LD_LIBRARY_PATH=/home/code &&
                      tail -f /dev/null"
        volumes:
            - code:/home/code
                  
volumes:
    code:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/server/Documents/FinalProject/FlushReload'

